---
- name: Site destroy | delete database
  mysql_db:
    name={{ db_name }}
    state=absent

- name: Site destroy | delete codebase
  file:
    path={{ sitepath }}
    state=absent
  sudo: true

- name: Site destroy | remove reference to host from local hosts file
  lineinfile:
      dest='/etc/hosts'
      state=absent
      line='127.0.0.1 {{ sitename }}'
  sudo: true
